apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: container-probe
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: container-probe
          servicePort: 80